name: HubMC
version: 1.0.1
main: com.github.mourthag.MainHubPlugin.Main
author: Mourthag
commands:
  port:
    usage: /port <list|set|delete> [server|location] [name] [ItemID] [Slot]
    description: List all, delete or set ports
    permission: ports.admin
    
permissions:
  ports.admin:
    default: false
    description: Allows you to manage ports